# Generated by Django 3.1.4 on 2020-12-07 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='background',
            field=models.PositiveIntegerField(choices=[(1, 'Background 1'), (2, 'Background 2'), (3, 'Background 3'), (4, 'Background 5')], default=1),
        ),
    ]
