# Generated by Django 3.1.4 on 2020-12-11 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RadioStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=40)),
                ('url', models.URLField()),
                ('description', models.TextField(max_length=1000)),
                ('genres', models.CharField(choices=[('p1', 'Modern pop'), ('r1', 'Rock'), ('c1', 'Classical'), ('n1', 'News')], max_length=3)),
                ('logo', models.ImageField(default='logos/default.jpg', upload_to='logos')),
            ],
        ),
        migrations.CreateModel(
            name='FavouritesList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.TextField(default='Playlist', max_length=40)),
                ('is_main', models.BooleanField(default=False)),
                ('radio_stations', models.ManyToManyField(default=None, to='radio.RadioStation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
