# Generated by Django 3.1.4 on 2020-12-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favouriteslist',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
