# Generated by Django 3.1.4 on 2020-12-11 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favouriteslist',
            old_name='is_main',
            new_name='is_user_default',
        ),
    ]
