# Generated by Django 3.1.4 on 2020-12-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0003_auto_20201212_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='slug',
            field=models.SlugField(default=2, editable=False),
            preserve_default=False,
        ),
    ]
