# Generated by Django 3.1.4 on 2021-01-09 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='background',
            field=models.CharField(choices=[('bg_1', 'Background 1'), ('bg_2', 'Background 2'), ('bg_3', 'Background 3'), ('bg_4', 'Background 4'), ('bg_4', 'Background 5'), ('bg_4', 'Background 6')], default='bg_1', max_length=4),
        ),
    ]
