# Generated by Django 3.1.4 on 2020-12-11 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='default_playlist',
        ),
    ]
