# Generated by Django 3.1.4 on 2020-12-06 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadioStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=40)),
                ('description', models.TextField(max_length=1000)),
                ('genres', models.CharField(choices=[('p1', 'modern pop'), ('r1', 'Rock'), ('c1', 'Classical'), ('n1', 'News')], max_length=3)),
                ('logo', models.ImageField(default='logos/default.jpg', upload_to='logos')),
            ],
        ),
        migrations.CreateModel(
            name='FavouritesList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.TextField(default='Playlist', max_length=40)),
                ('radio_stations', models.ManyToManyField(default=None, to='radio.RadioStation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='BackgroundChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.PositiveIntegerField(choices=[(1, 'Background 1'), (2, 'Background 2'), (3, 'Background 3'), (4, 'Background 5')], default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile')),
            ],
        ),
    ]
