# Generated by Django 3.1.4 on 2020-12-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavouritesList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RadioStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('genres', models.CharField(choices=[('p1', 'modern pop'), ('r1', 'Rock'), ('c1', 'Classical'), ('n1', 'News')], max_length=3)),
            ],
        ),
    ]
