# Generated by Django 3.1.4 on 2020-12-06 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiostation',
            name='url',
            field=models.URLField(default='radio-url'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='radiostation',
            name='genres',
            field=models.CharField(choices=[('p1', 'Modern pop'), ('r1', 'Rock'), ('c1', 'Classical'), ('n1', 'News')], max_length=3),
        ),
    ]
