# Generated by Django 3.1.4 on 2020-12-07 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0002_auto_20201206_2234'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackgroundChoice',
        ),
    ]
